---
title: "Confronting HIV as a Stereotypical Infection of Sexual Minorities"
author: "Nikodem Lewandowski"
format:
    pdf:
        include-in-header: quartoStyle.sty
        mainfont: Times New Roman
        sansfont: Times New Roman
urlcolor: blue
fontsize: 12pt
bibliography: [LIBhiv.bib]
execute: 
  cache: true
---

```{python packages}
#| include: false

#execute: 
#  cache: true

# loading packages

import seaborn as sns
# import arviz as az           arviz error
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
import networkx as nx
import subprocess


# Complex data wrangling and model building is kept in seperate files,
# please read the readme file to navigate easily through the project


# color palletes:

pallette_colBlindPair1 = ["#DDCC77", "#88CCEE"] 
fancyMine1 = ["#024b7a", "#44b7c2"]


```


\begin{abstract}

\textbf{Abstract:} My goal is to challenge the stereotype associating HIV infection primarily with non-heteronormative males. Using Bayesian logistic regression models and risk profile analysis, I argue that risky behaviors, rather than sexual identity or gender, are the primary drivers of HIV infection.

The research employs a dataset created from a survey conducted in Polish HIV diagnostic centers. Poland is currently experiencing a rise in new HIV infections, with non-heteronormative males constituting the majority of new cases. However, the findings reveal that high-risk behavior serves as a better predictor of infection than gender or sexual identity. This highlights the complexity of the factors driving new infections among non-heteronormative males.

This research underscores the critical need for comprehensive awareness and testing to combat the ongoing HIV epidemic. It prompts a reevaluation of the assumptions surrounding the causes of the domination of non-heteronormative males among the newly infected.

\end{abstract}


\vspace{12mm}


## Introduction

The year 1980 is proclaimed as the start of the HIV epidemic. Since then, scientists around the world have been diligently working to find new ways to protect the global public from infection and treat those who have been infected [@Sharp2011]. Thanks to increased awareness and breakthroughs in medical achievements, it is now easier to detect the HIV virus in an individual's blood. We also know that using condoms and PrEP^[PrEP, which stands for pre-exposure prophylaxis, is a medication that significantly reduces the risk of HIV infection.] is an effective means of preventing infection.          

As a result, the global number of new infections has significantly decreased, thanks to advanced treatment methods, infected individuals can now enjoy a lifespan similar to uninfected people. The global infection rate continues to decline, as reported by @unaidsGlobalAIDS. However, in some well-developed countries, there is a concerning rise in new HIV infections, particularly noticeable in the European Union (EU) where the number of new infections has been on the rise [@EUHIV20212022]. One contributing factor is the global COVID-19 epidemic, which has discouraged people from getting tested for HIV, as evidenced by our dataset. Poland is one of the countries experiencing a worsening situation.        

From the beginning of the HIV epidemic, this virus has been associated with non-heteronormative individuals, predominantly males. During those years, gay men faced less acceptance compared to other sexual identities. Gay clubs provided a safe and accepting environment where anonymity was valued, and engaging in anonymous sexual encounters was not uncommon. Before the awareness of HIV, the use of condoms was less prevalent, making such sexual behavior highly risky. 

PROBLEMATIC PASSAGE The stereotype of HIV as "the disease of gays" still persists. In this study, I aim to challenge this stereotype by analyzing the causes of HIV infections. The main questions addressed in this work are:

- Do males in general have a higher probability of contracting HIV?
- Are homosexual individuals at a higher risk than heterosexuals?
- Is HIV primarily an infection among gay males, and does the stereotype hold true that there is something 'special' about this group explaining this phenomenon?

I will attempt to answer these questions by analyzing surveys^[Link to the github repository of this project can be found [here](https://github.com/Niklewa/hivPKDproject)]  conducted in Polish HIV testing centers known as PKDs (Pol. [Punkt Konsultacyjno Diagnostyczny](https://aids.gov.pl/pkd/) - Diagnostic Consultation Center). At least one such center exists in every major administrative region in Poland (Voivodeship). Testing at these centers is always anonymous, free of charge, and safe. Medical professionals at these centers interview clients and qualify them for testing, including a section of the survey focused on their sexual history.

The data were collected from 2015 to 2022,^[The dataset was obtained with the cooperation of PKD officials, the files are available on my GitHub project.] comprising responses from over 250,000 individuals. However \textbf{it is not} a random sample, people that go to test themselves usually have a reason for that /todo{maybe vis of causes of test?}. It is important to note that this dataset does not provide accurate information on the number of new infections, as there are various other places in Poland where HIV infection can be diagnosed. Therefore, our focus is on the survey questions. 

The visualizations below depict the demography of the survey (@fig-demography). The left plot illustrates the gender distribution.^[22 individuals identified as 'Different' gender; however, their number is too small to be considered significant and is therefore excluded from the analysis] Notably, the majority of clients are males, and non-heteronormative males constitute half of all male clients, a higher proportion than in the general population. Females, on the other hand, are represented more proportionally.

The plot on the right illustrates the sexual identity and gender among the individual that received HIV-positive test result^[Individuals considered HIV-positive in this analysis underwent two tests: the initial screening test, which yielded a positive result, and a second test that measured the amount of HIV virus in the blood, confirming the initial result.]. Approximately $70\%$ of HIV-positive individuals identify as non-heteronormative males. This result raises the need for further analysis, as it indicates that non-heteronormative males are more susceptible to infection. It is worth noting that this group seems to be aware of the risk, as they are overrepresented among those who regularly get tested.

One thing to note, due to the survey's anonymity, individuals who test themselves regularly will be counted as separate entries, potentially inflating the representation of this group. This might be one of the reasons for their overrepresentation.

The question arises: Is there indeed something distinctive about non-heteronormative males that makes them more susceptible to HIV infection? I will attempt to answer this question by examining causal relationships among various predictors, with a focus on identifying variables that best predict HIV positivity.

In the first section, I will begin by establishing a basic logistic regression model that demonstrates the relationship between gender, sexual identity, and the probability of HIV infection. The subsequent step involves an exploration of whether a causal connection between these variables is plausible. Following this, I delve into the quest for more robust predictors. During this investigation, I identify superior predictors and formulate a risk profile (RP), which exhibits a higher probability of infection.

Remarkably, the group most likely to be within the RP comprises non-heteronormative males, shedding further light on the causal relationships among the aforementioned predictors. This relationship is visually represented with a Directed Acyclic Graph (DAG) at the conclusion of the study

These findings challenge the stereotype, asserting that the primary cause of HIV infection is not one's sexual identity but rather risky behavior.


```{python}
#| label: fig-demography
#| echo: false
#| fig-cap: The left plot shows the dataset's gender and sexual identity distribution, while the right plot displays the ratio among those who tested positive.
#| fig-pos: 'H'
#| warning: false
#| message: false


# File containing the wrangling of a dataset: ../pythonCode/DataWranglinfForHomoCasualityCheck.py

PKD_model_DF = pd.read_csv("../dataBits/PKD_model_DF.csv")
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# 1st plot - Gender Distribution by Sexual Identity
grouped_data = PKD_model_DF.groupby(["Płeć", "Hetero_normative"]).size().unstack(fill_value=0)
grouped_data = grouped_data.loc[grouped_data.index != 'I']



ax1 = grouped_data.plot(kind="bar", stacked=True, color=fancyMine1, width=0.4,  ax=axes[0])
ax1.set_xlabel("")
ax1.set_title("Gender Distribution by Sexual Identity", fontsize=24, y=1.1)
ax1.legend(labels=["Non-Hetero norm.", "Hetero norm."], frameon=False, fontsize= 18, loc='upper left', bbox_to_anchor=(0, 1))
ax1.set_xticklabels(['Females', 'Males'], rotation=0)
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax1.grid(False)

ax1.tick_params(axis='y', labelsize=18)
ax1.tick_params(axis='x', labelsize=18)

# 2nd plot - HIV Positive Ratio
category_counts = PKD_model_DF.groupby(["Płeć", "Hetero_normative", "HIV"]).size().reset_index(name='Count')
category_counts = category_counts.loc[category_counts['Płeć'] != 'I']
category_counts = category_counts.loc[category_counts['HIV'] != 0]
category_counts['Percentage'] = category_counts['Count'] / sum(category_counts['Count'])

ax2 = sns.barplot(data=category_counts, x='Płeć', y='Percentage',
                   hue='Hetero_normative', palette=fancyMine1, saturation=1,  ax=axes[1])
ax2.set_xlabel('')
ax2.set_ylabel('')
ax2.set_title('HIV Positive', fontsize=22, y=1.1)
ax2.set_xticklabels(['Females', 'Males'], rotation=0)
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.legend().set_visible(False)

ax2.tick_params(axis='y', labelsize=18)
ax2.tick_params(axis='x', labelsize=18)

ax2.grid(False)


from matplotlib.ticker import FuncFormatter
def percentage_formatter(x, pos):
    return f'{x:.0%}'  # Display percentage without decimal places

ax2.yaxis.set_major_formatter(FuncFormatter(percentage_formatter))

ax2.set_yticks([0.0, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70])



plt.tight_layout()
plt.show()


```


## Exploring HIV Risk Factors and Predictors

Let's begin by constructing a model aimed at predicting HIV infection based on known variables: gender and sexual identity. All statistical models in this project were built using the 'numpyro' package in Python.^[It's a simplified version of the 'pyro' package, both of which focus on providing tools for probabilistic data analysis, including the creation of advanced hierarchical models. The package documentation can be found [here](https://num.pyro.ai/en/latest/index.html#introductory-tutorials).] 
The Bayesian logistic regression model below examines the interplay between HIV infection (HIV), heteronormativity (Hetero_normative), and gender (Gender_encoded). All of my models follow the same template. Model parameters include the intercept term 'a' representing baseline log-odds of HIV infection, coefficients 'b' and 'c' quantifying the effects of heteronormativity and gender, respectively. The logit transformation combines these factors to calculate log-odds. Priors in the form of normal distributions are assigned to model parameters. When it comes to priors, I have selected modest parameters that have a limited impact on the posterior distributions. The relatively large size of the dataset exerts a more substantial influence. A binomial likelihood function is used for observed HIV infection data, updating parameter beliefs. The model is run using the No-U-Turn Sampler (NUTS), a variant of Markov Chain Monte Carlo (MCMC). Here's a template of what the model looks like:

\footnotesize

```{python}
#| eval: false

dat_listGender = {
    'HIV': PKD_model_DF.HIV.values,
    'Hetero_normative': PKD_model_DF.Hetero_normative.values,
    'Gender_encoded': PKD_model_DF.Gender_encoded.values,
    }

def model_hetero_Gender(Hetero_normative, Gender_encoded, HIV=None):     
    a = numpyro.sample("a", dist.Normal(0, 1.5))  
    b = numpyro.sample("b", dist.Normal(0, 0.5).expand([2])) 
    c = numpyro.sample("c", dist.Normal(0, 0.5).expand([2])) 

    logit_p = a + b[Hetero_normative] + c[Gender_encoded]
    numpyro.sample("HIV", dist.Binomial(logits=logit_p), obs=HIV)

HIV_HetreoNorm_Gender = MCMC(NUTS(model_hetero_Gender),
    num_warmup=500, num_samples=500) 
HIV_HetreoNorm_Gender.run(random.PRNGKey(0), **dat_listGender)



```


\normalsize

The model defines following parameters: a, the intercept term in the logistic regression model. It captures the baseline log-odds of HIV infection when all other predictors are zero, b and c which are vectors of coefficients assoicated with given predictors. 

The log-odds of HIV infection (`logit_p`) are calculated as a linear combination of the intercept `a`, the effects of `Hetero_normative` (`b`), and the effects of `Gender_encoded` (`c`). The logistic function will later transform these log-odds into probabilities.

 In Bayesian modeling, prior distributions are assigned to model parameters to express beliefs or uncertainty before observing data. In this example, normal distributions are used as priors for `a`, `b`, and `c`. These distributions specify the range of plausible values for each parameter. The priors are not relying on any specific data, they are realtively modest, the size of data is big, so it is not a problem.

Now, let's explore the relationship between our demographic predictors and the likelihood of being HIV positive. In @fig-modelsexhetero, you can examine the predictions generated by the model, which incorporated gender and sexual identity as predictors. The violin plots depict the distribution of predictions, reflecting the marginal posterior densities derived through sampling techniques, rather than providing single point estimates. This approach aligns with the Bayesian methodology, as it conveys more information than, for instance, just a mean or statistical tests.



```{python}
#| label: fig-modelsexhetero
#| fig-cap: This visualization displays the predictions generated by the logistic regression model trained on the dataset. The violins depict the probability distribution of HIV acquisition predictions with respect to gender and sexual identity.
#| echo: false
#| warning: false
#| results: hide
#| message: false
#| fig-pos: 'H'

# File containing the model training: ../pythonCode/MLogit_Partners_Heteronorm_gender.py

with open('../savedBits/postDF_Hetero_Gender.pkl', 'rb') as f:
    postDF_Hetero_Gender = pickle.load(f)


gender_mapping = {0: "Females", 1: "Males"}

postDF_Hetero_Gender['Gender'] = postDF_Hetero_Gender['Gender'].replace(gender_mapping)

sex_ident_order = ['Hetero', 'Non-hetero']


postDF_Hetero_Gender['SexIdent'] = pd.Categorical(postDF_Hetero_Gender['SexIdent'], categories=sex_ident_order, ordered=True)

sns.set(style="whitegrid", font_scale=0.85)  # Adjust font_scale as needed (0.9 makes it slightly smaller)
g = sns.FacetGrid(postDF_Hetero_Gender, col='Gender' ) 
g.map_dataframe(sns.violinplot, x="SexIdent", hue='SexIdent', y="Probability",
palette= fancyMine1)# pallete here

g.set_axis_labels('', 'Probability')
g.set_titles(col_template = '{col_name}')

g.fig.subplots_adjust(top=0.77)
g.fig.suptitle('Probability of HIV Infection')

plt.show()

```


Comparatively, the differences are easily visible, with non-heterosexual males appearing to be at the highest risk of infection when we consider no other factors. However, there are also distinctions between genders, with males once again being at greater risk. In fact, there are many publications supporting the claim that women are less susceptible to infection compared to men [@Beyrer2012]. The risk of a woman contracting HIV during intercourse with an infected person is lower than that for a man.

 
```{python}
#| label: fig-dagwrong
#| fig-cap: DAG representing the naive relation between variables resembling the first model. 'U' stands for unobserved, ~H for non-hetero, while the rest of the labels are self-explanatory.
#| echo: false
#| warning: false
#| message: false
#| results: hide
#| fig-align: center




dagWrong = nx.DiGraph()
dagWrong.add_edges_from([('Male', 'HIV'), ('~H', 'HIV'), ('U', 'HIV')])

# Define node colors
node_colors = {
    'Male': '#D1E5F4',  
    '~H': '#D1E5F4',  
    'U': '#AEAEAE',        
    'HIV': '#D1E5F4'    
}

plt.figure(figsize=(3.5, 2.7))

pos = nx.spring_layout(dagWrong, seed=42)
nx.draw(dagWrong, pos, with_labels=True, node_color=[node_colors[node] for node in dagWrong.nodes()], node_size=1000)


plt.show()


```

But does this information provide us with insights into causal relationships? It certainly provides some insights, but we should consider a wide range of underlying causes that might be responsible for such results. Let's examine a Directed Acyclic Graph (DAG), represented as @fig-dagwrong, which corresponds to the rationale of the initial model.


The reasoning appears to be somewhat limited, suggesting that there is something 'special' about males and non-heterosexual individuals that makes them more prone to HIV infection. The node representing 'Unobserved' deserves special attention, as it encompasses all other potential factors that could lead to an HIV infection, such as transmission through a used needle. The primary achievement of this reasoning is to reinforce the stereotype that HIV is primarily an infection of homosexual males. Let's now shift our focus to the main objective of this work. We aim to identify predictors that may offer a better explanation for HIV infection, potentially going beyond the simplistic division between heterosexual and non-heterosexual individuals.

What predictors should we consider? The risk factors for HIV have been the subject of numerous studies, and we can leverage their findings in our analysis. According to the World Health Organization (WHO), the most common risk factors include: 


>   - having condomless anal or vaginal sex;
    - having another sexually transmitted infection (STI) such as syphilis, herpes, chlamydia, gonorrhoea and bacterial vaginosis;
    - engaging in harmful use of alcohol and drugs in the context of sexual behaviour;
    - sharing contaminated needles, syringes and other injecting equipment and drug solutions when injecting drugs;
    - receiving unsafe injections, blood transfusions and tissue transplantation, and medical procedures that involve unsterile cutting or piercing; and
    - experiencing accidental needle stick injuries, including among health workers. [@whoAIDS]

Since we are specifically interested in examining transmission based on sexual activities, we will exclude injective drug users and marginal cases of medical accidents where infection might occur through contact with a patient's blood. However, we can add the variable representing the number of sexual partners (per year) a person has. The rationale here is simple: more partners mean more opportunities for infection. Additionally, we will focus on anal sex as a chosen risk factor, given that it is the most high-risk sexual activity.^[We could have considered oral sex and the risk of not using protection during oral sex, but due to the ambiguous distinction between passive and active oral sex, the data variable seems unreliable. There is common confusion between what constitutes passive and active oral sex. By definition, being on the receptive end is called passive, while using one's mouth is called active. However, in the gay community, the division between tops and bottoms (actives and passives) often perceives receptive oral sex as an active activity.]


```{python}
#| echo: false
#| fig-align: center
#| label: fig-violinbigmales
#| fig-cap: In this visualization, you can observe various categories considered as contributors to a risky profile. This plot focuses solely on males.

# File containing the model training: ../pythonCode/MLog_homRIskProfiler.py

DFPost_HIVRiskProfile = pd.read_csv("../savedBits/DFPost_HIVRiskProfile.csv")

sns.set(style="whitegrid")

custom_palette = ["#8D4585", "#56B4E9", '#FFC20A'] 

from matplotlib.lines import Line2D

postDF_RiskProfileMales = DFPost_HIVRiskProfile[DFPost_HIVRiskProfile['Gender'] == 1]
postDF_RiskProfileFemales = DFPost_HIVRiskProfile[DFPost_HIVRiskProfile['Gender'] == 0]

postDF_Alco1 = postDF_RiskProfileMales[postDF_RiskProfileMales['Sex_alcohol'] == 1]
postDF_Alco0 = postDF_RiskProfileMales[postDF_RiskProfileMales['Sex_alcohol'] == 0]

fig, axes = plt.subplots(2, 1, figsize=(14.5, 8.5))  

sns.violinplot(data=postDF_Alco1, x="AnalPosition", y="Probability", hue="PartnersNum", order= ['no', 'active', 'passive', 'vers'], ax=axes[0], palette=custom_palette)
axes[0].set_title("Sex After Alcohol", fontsize=20)
axes[0].set_xlabel("Anal Sex Preference", fontsize=20)
axes[0].set_ylabel("Probability", fontsize=20)

axes[0].tick_params(axis='y', labelsize=18)
axes[0].tick_params(axis='x', labelsize=18)

legend_handles = [Line2D([0], [0], marker='o', color='w', markerfacecolor=custom_palette[0], markersize=10, label='1-10'),
                  Line2D([0], [0], marker='o', color='w', markerfacecolor=custom_palette[1], markersize=10, label='11-50'), # '1-10', '11-50', 'above_51'
                  Line2D([0], [0], marker='o', color='w', markerfacecolor=custom_palette[2], markersize=10, label='above 51')]


legend1 = axes[0].legend(title="Number of Partners", loc="upper left", handles=legend_handles, fontsize=18)
legend1.get_title().set_fontsize('18')
legend1.get_frame().set_alpha(None)

# Plot for gender = 0
sns.violinplot(data=postDF_Alco0, x="AnalPosition", y="Probability", hue="PartnersNum", order= ['no', 'active', 'passive', 'vers'], ax=axes[1], palette=custom_palette)
axes[1].set_title("No Sex After Alcohol", fontsize=20)
axes[1].set_xlabel("Anal Sex Preference", fontsize=20)
axes[1].set_ylabel("Probability", fontsize=20)

axes[1].tick_params(axis='y', labelsize=18)
axes[1].tick_params(axis='x', labelsize=18)


legend2 = axes[1].legend(title="Number of Partners", loc="upper left", handles=legend_handles, fontsize=18)
legend2.get_title().set_fontsize('18')
legend2.get_frame().set_alpha(None)

# unifying y axis values
combined_data = DFPost_HIVRiskProfile["Probability"]
y_min = combined_data.min()
y_max = combined_data.max()
axes[0].set_ylim(y_min, y_max)
axes[1].set_ylim(y_min, y_max)

plt.suptitle("Probability of Getting HIV Infected (Males Only)", fontsize=22)

plt.tight_layout()
plt.show()

```




```{python}
#| echo: false
#| fig-align: center
#| label: fig-violinbigfemales
#| fig-cap: This is a twin visualization covering risky categories. This plot focuses exclusively on females, and the difference in the probability of getting infected is striking.


# File containing the model training: ../pythonCode/MLog_homRIskProfiler.py

sns.set(style="whitegrid")

custom_palette = ["#8D4585", "#56B4E9", '#FFC20A'] 


postDF_Alco1 = postDF_RiskProfileFemales[postDF_RiskProfileFemales['Sex_alcohol'] == 1]
postDF_Alco0 = postDF_RiskProfileFemales[postDF_RiskProfileFemales['Sex_alcohol'] == 0]

fig, axes = plt.subplots(2, 1, figsize=(14.5, 8.5))  

sns.violinplot(data=postDF_Alco1, x="AnalPosition", y="Probability", hue="PartnersNum", order= ['no', 'active', 'passive', 'vers'], ax=axes[0], palette=custom_palette)
axes[0].set_title("Sex After Alcohol", fontsize=20)
axes[0].set_xlabel("Anal Sex Preference", fontsize=20)
axes[0].set_ylabel("Probability", fontsize=20)
axes[0].tick_params(axis='y', labelsize=18)
axes[0].tick_params(axis='x', labelsize=18)

legend_handles = [Line2D([0], [0], marker='o', color='w', markerfacecolor=custom_palette[0], markersize=10, label='1-10'),
                  Line2D([0], [0], marker='o', color='w', markerfacecolor=custom_palette[1], markersize=10, label='11-50'), # '1-10', '11-50', 'above_51'
                  Line2D([0], [0], marker='o', color='w', markerfacecolor=custom_palette[2], markersize=10, label='above 51')]


legend1 = axes[0].legend(title="Number of Partners", loc="upper left", handles=legend_handles, fontsize=20)
legend1.get_title().set_fontsize('18')
legend1.get_frame().set_alpha(None)

# Plot for gender = 0
sns.violinplot(data=postDF_Alco0, x="AnalPosition", y="Probability", hue="PartnersNum", order= ['no', 'active', 'passive', 'vers'], ax=axes[1], palette=custom_palette)
axes[1].set_title("No Sex After Alcohol", fontsize=20)
axes[1].set_xlabel("Anal Sex Preference", fontsize=20)
axes[1].set_ylabel("Probability", fontsize=20)
axes[1].tick_params(axis='y', labelsize=18)
axes[1].tick_params(axis='x', labelsize=18)

legend2 = axes[1].legend(title="Number of Partners", loc="upper left", handles=legend_handles, fontsize=20)
legend2.get_title().set_fontsize('18')
legend2.get_frame().set_alpha(None)

# unifying y axis values
combined_data = DFPost_HIVRiskProfile["Probability"]
y_min = combined_data.min()
y_max = combined_data.max()
axes[0].set_ylim(y_min, y_max)
axes[1].set_ylim(y_min, y_max)

plt.suptitle("Probability of Getting HIV Infected (Females Only)", fontsize=22)

plt.tight_layout()
plt.show()

```

In figures: @fig-violinbigmales and @fig-violinbigfemales, you can observe visualizations of predictions created by the logistic regression model for males and females, respectively. The model utilized the following predictors: gender, binned number of sexual partners (per year), preference for anal intercourse, and engaging in sexual activity under the influence of alcohol. There is a striking contrast between males and females. Even when women fall into the most high-risk profile category, the risk of infection remains considerably lower than for males. As mentioned earlier, studies support these findings, suggesting that women are significantly less susceptible to HIV infection for biochemical reasons.

All these factors contribute to the definition of the most high-risk profile: a male with more than 51 sexual partners, a preference for versatile anal intercourse, and engaging in alcohol-induced sex. It's evident that each of these categories individually increases the probability of infection.

## Defining a High-Risk Profile for HIV Infection

The next step involves defining a Risk Profile (RP) that maximizes the chances of HIV infection. This profile will \textbf{ exclude sexual identity and gender} in order to empasize the influence of other variables. I will introduce the profile as a new binary variable in the dataset. This approach is simpler than constructing a model that accommodates all these variables and creates different categories for each of them.   

The variables I will use to create the RP are:     

- Alcochol-induced sex,
- Having more than 10 sexual partners per year, 
- Anal sex preference: passive or versatile, 
- Anal sex protection use: sometimes or never.       


```{python}
#| label: fig-riskprofgenderhiv
#| fig-cap: The visualization represents the probability of getting infected for RP holders, divided into females and males.
#| echo: false
#| results: hide
#| warning: false
#| message: false


# File containing the model training: ../pythonCode/MLog_DataHIGHRISKProfile.py

with open('../savedBits/DFPOST_HIv_risk_gender.pkl', 'rb') as f:
    DFPOST_HIv_risk_gender = pickle.load(f)

sns.set(style="whitegrid", font_scale=0.85) 

gender_mapping = {0: "Females", 1: "Males"}
DFPOST_HIv_risk_gender['Gender'] = DFPOST_HIv_risk_gender['Gender'].replace(gender_mapping)

risk_mapping = {0: "Not risky", 1: "Risky"}
DFPOST_HIv_risk_gender['RiskFactor'] = DFPOST_HIv_risk_gender['RiskFactor'].replace(risk_mapping)


g = sns.FacetGrid(DFPOST_HIv_risk_gender, col='Gender')
g.map_dataframe(sns.violinplot, x="RiskFactor", hue="RiskFactor", y="Probability",
palette=fancyMine1)
plt.xlabel("")
plt.ylabel("Probability")

g.set_axis_labels('', 'Probability')
g.set_titles(col_template = '{col_name}')


g.fig.subplots_adjust(top=0.77)
g.fig.suptitle('Probability of HIV Infection')

plt.show()


```



In @fig-riskprofgenderhiv, which represents the probability of infection for the RP, we can observe that the probability for males in the RP group is higher than the probability in our first model (represented in @fig-modelsexhetero), which showed a high probability of infection for non-hetero males. This suggests that RP profile holders are at a greater risk of infection than non-hetero males. But what is the relationship between these two variables? We will test this with our next model.

```{python}
#| echo: false
#| label: fig-twinriskprob
#| fig-cap: "The visualization represents the probability of being in RP, with a division by gender on the left and by sexual identity on the right."
#| results: hide
#| warning: false
#| message: false

# File containing the model training: ../pythonCode/MLog_DataHIGHRISKProfile.py

with open('../savedBits/DFPost_Post_RISK_NormGendernoHetero.pkl', 'rb') as f:
    DFPost_Post_RISK_NormGendernoHetero = pickle.load(f)



fig, axs = plt.subplots(1, 2, figsize=(12, 6), sharey=True,)


gender_mapping = {"0": "Females", "1": "Males"}
DFPost_Post_RISK_NormGendernoHetero['Gender'] = DFPost_Post_RISK_NormGendernoHetero['Gender'].replace(gender_mapping)

sns.violinplot(data=DFPost_Post_RISK_NormGendernoHetero, x="Gender", y="Probability", ax=axs[0], palette= fancyMine1)
axs[0].set_xlabel("")
axs[0].tick_params(axis='y', labelsize=18)
axs[0].tick_params(axis='x', labelsize=18)

axs[0].set_ylabel("Probability", fontsize=18)


# second vis

with open('../savedBits/DFPost_POST_RISK_Hetero.pkl', 'rb') as f:
    DFPost_POST_RISK_Hetero = pickle.load(f)


hetero_mapping = {"0": "Non hetero", "1": "Hetero"}
DFPost_POST_RISK_Hetero['HeteroNorm'] = DFPost_POST_RISK_Hetero['HeteroNorm'].replace(hetero_mapping)


sns.violinplot(DFPost_POST_RISK_Hetero, x="HeteroNorm", y="Probability", ax=axs[1], order= ['Hetero', 'Non hetero'], palette= fancyMine1)
axs[1].set_xlabel("")
axs[1].set_ylabel("")
axs[1].tick_params(axis='y', labelsize=18)
axs[1].tick_params(axis='x', labelsize=18)


axs[0].set_ylim(0, 0.06)
axs[1].set_ylim(0, 0.06)

plt.tight_layout()

fig.subplots_adjust(top=0.83)
fig.suptitle("Probability of the Risk Profile", fontsize=22)

plt.show()



```


In the pair of visualizations in @fig-twinriskprob, we can see the models that were given gender and sexual identity as predictors to predict being in the most risky group. As it can be seen, non-hetero individuals and males have the highest probability of being in that group.

Returning to representing the causes of HIV infection, the variables that increase the probability of infection are better at getting you infected. Therefore, considering them as causes is more reasonable. The Directed Acyclic Graph (DAG) that will represent the relationship between the considered variables, after our analysis, will look something like the one shown in @fig-postdag.


```{python}
#| label: fig-postdag
#| fig-cap: 'This DAG represents the relationship between demographic variables, the RP (risk profile), and HIV infection.'
#| echo: false



dag2 = nx.DiGraph()
dag2.add_edges_from([('Male', 'RP'), ('~H', 'RP'), ('U', 'RP'), ('RP', 'HIV')])

# Define node colors
node_colors = {
    'Male': '#D1E5F4',  
    '~H': '#D1E5F4',  
    'U': '#AEAEAE',        
    'RP': '#D1E5F4',  
    'HIV': '#D1E5F4' 
}


plt.figure(figsize=(3.5, 2.7))

pos = nx.spring_layout(dag2, seed=42)
nx.draw(dag2, pos, with_labels=True,
    node_color=[node_colors[node] for node in dag2.nodes()], node_size=1000)


plt.show()


```

## Conclusions

In the @fig-postdag, the DAG represents the relationship between the predictors we analyzed. It seems to represent cause and effect more realistically than just relying on the notion that non-hetero males are 'special' in some way, leading to HIV infection. In fact, non-hetero males have a high probability of being in an RP group, and risky behaviors associated with RP status are the causes of HIV infection. This includes having anal intercourse and a high number of sexual partners, which is associated with non-hetero males. The reason why non-hetero males choose to be in that group is not known, represented by the Unobserved node.

Is the stereotype true then? Well, non-hetero males are at the highest risk of getting HIV infected, but their sexual identity is not a direct cause of that. Hetero sexual males who enjoy similar activities, and thus are in an RP, also have higher chances of getting infected. The more direct cause is risky behavior, and non-hetero males tend to engage in more risky behaviors. Therefore, the story is more complex. The findings of this paper support the claim that: \textbf{the sole fact of being a non-hetero person does not make you more susceptible to getting HIV infected}.

An interesting observation in the field of interest to specialists from different scientific branches is the fact that women get infected far less often than males. 

One thing worth noting is the concerning growth of new HIV infections in Europe. The mentioned stereotype might have a negative effect on public opinion, as hetero people might feel too confident about not getting infected, assuming this infection is mainly associated with non-hetero males. This analysis has shown that there is a risky behavior pattern that all people should be aware of, as it can lead to HIV infection. In fact, as we have seen at the beginning, hetero males tend to test themselves much less often than non-hetero males.

#  References {-}